name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout code
      uses: actions/checkout@v3
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_PASS }}
    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@v4
      with:
        images: mnacey/arm-test
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
      # https://github.com/docker/setup-buildx-action
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Build the Amazon Docker Image
      run: docker buildx build  . --file amz/Dockerfile --tag mnacey/arm-test:amz --platform linux/amd64,linux/arm64 --push
    - name: Build the Debian Docker Image
      run: docker buildx build  . --file deb/Dockerfile --tag mnacey/arm-test:deb --platform linux/amd64,linux/arm64 --push
    - name: Build the Ubuntu Docker Image
      run: docker buildx build  . --file ubuntu/Dockerfile --tag mnacey/arm-test:ubuntu --platform linux/amd64,linux/arm64 --push

